In [1]:
import numpy as np

In [34]:
a=np.array([[1,4,5],[2,5,3],[1,1,8]])
b=np.array([0,0,1])
c=np.array([0.2,0.3,0.5])
d=np.array([1,0,0])

In [20]:
a=a/10

In [21]:
a2=np.matmul(a,a)


In [22]:
a3=np.matmul(a2,a)

In [26]:
np.matmul(b,a2)

array([0.11, 0.17, 0.72])

In [27]:
np.matmul(c,a3)

array([0.1251, 0.2388, 0.6361])

In [28]:
a5=np.matmul(a3,a2)

In [35]:
np.matmul(d,a5)

array([0.12419, 0.2345 , 0.64131])

In [42]:
A=np.array([[0/5,2/5,2/5],[3/10,5/10,2/10],[1/11,3/11,7/11]])


In [44]:
A

array([[0.        , 0.4       , 0.4       ],
       [0.3       , 0.5       , 0.2       ],
       [0.09090909, 0.27272727, 0.63636364]])